### ISSUE TITLE
Can't find rabbit-converter/rabbit-php on packagist

### ISSUE THREAD

**Issue by Mr-Zer0** [Rabbit-Converter/Rabbit-PHP#3]
I have run composer require rabbit-converter/rabbit-php. I'v got could not find error. And I've search at packagist.org manually. There is no result for rabbit-php

**Comment by yelinaung** [comment]
Ko @nyanlynnhtut, care to take a look at this ?

**Comment by yelinaung** [comment]
Hmm Ko @Mr-Zer0 I think what you are looking for is available at https://packagist.org/packages/rabbit-converter/rabbit-php. 
Closing this for now.

**Comment by Mr-Zer0** [comment]
```
[InvalidArgumentException]
  Could not find package rabbit-converter/rabbit-php at any version for your
  minimum-stability (stable). Check the package spelling or your minimum-stability
```

**Comment by saturngod** [comment]
Yes. it happen to me. Look like composer has some changes. @nyanlynnhtut , can you check ?

**Comment by yelinaung** [comment]
@Mr-Zer0 @saturngod  The `version` is `dev-master`. Not `stable`.
Can you try again with version `"rabbit-converter/rabbit-php": "dev-master"`

It seems working for me perfectly.

<img width="413" alt="1 zsh - - - -" src="https://cloud.githubusercontent.com/assets/275120/8770661/9ede303e-2edb-11e5-8ef6-9aa13d609515.png">

**Comment by saturngod** [comment]
composer require rabbit-converter/rabbit-php:"dev-master"

is working. Need to update on readme.
