### ISSUE TITLE
Problem With Zawgyi One

### ISSUE THREAD

**Issue by naingyy** [Rabbit-Converter/Rabbit-PHP#5]
This library work very well converting Zawgyi <=> Unicode.But,a little problem with ZawgyiOne.Thanks.

**Comment by yelinaung** [comment]
@seven9 Could you provide more information such as 
- your input text
- your expected text
- and current results

Thanks!

**Comment by yenyint** [comment]
Hi @yelinaung Please see details below 

Converting ZawgyiOne to Unicode 

```
Rabbit::zg2uni('ေနေကာင္းလား');
//return "ဝဝေနဝဝေကဝာဝငဝ်ဝးဝလဝာဝးဝ"

```

Thanks!

**Comment by saturngod** [comment]
What font are you using ? It was not happen to me for zawgyi 2008 and zawgyi 2009 font.

Regards,

Htain Lin Shwe

**Comment by yenyint** [comment]
Hi @saturngod  Pls see in pic

![zawgyi](https://cloud.githubusercontent.com/assets/8743514/18375552/60f9da30-767d-11e6-98f9-630b6b52fa65.png)

Thanks!

**Comment by saturngod** [comment]
It may not be font problem. It may be problem of input text. What keyboard are you using ? How did you get text from where ? If it is not typing and copy txt from pdf or somewhere, it may be problem of original text.

Can you try in http://www.rabbit-converter.org/Rabbit/

Regards

Saturngod

**Comment by yenyint** [comment]
Hi @saturngod 

Thanks for your help. Yes it can be my keyboard problem.Can u tell me please
which keyboard is best for zawgyi.

Thanks!

**Comment by saturngod** [comment]
@seven9 I copied and paste your text in http://www.rabbit-converter.org/Rabbit/

It's working fine. There is no problem. Can you give me the real text that you have problem ?

**Comment by yenyint** [comment]
@saturngod I also tested that way bro but I can't find out what my problem is.My process is when user input text are zawgyi and submmit form I wanna convert to Unicode and save it into database.When I retrive data from database happen this problem.

I use this library https://github.com/setkyar/mmfont and everything Ok.But I just wanna your library better.I don't know difference between this two library bro.

Thanks Bro!

**Comment by saturngod** [comment]
So, when you receive on DB , value is not correct and extra ဝဝဝ ? In database , it's extra ဝ or after retrieve , you receive extra ဝ ?

**Comment by saturngod** [comment]
it may be problem of PHP version, I will check PHP version.

**Comment by saturngod** [comment]
@nyanlynnhtut @Arkar-Aung can you help me to check this issue ?

**Comment by yenyint** [comment]
@saturngod Yes Bro i receive extra o.I am using laravel homestead with php 7.

Thanks!

**Comment by saturngod** [comment]
extra o 

in db ?

or  fetch result from db with php ?

**Comment by nyanlynnhtut** [comment]
@saturngod Yes. It's happen in PHP library. Extra "wa" are include for every letter.
Check this

http://sandbox.onlinephpfunctions.com/code/3448a7afeca0b64d22b55b8dc6143a3f92d78d13

Note: Not only PHP 7.

**Comment by saturngod** [comment]
@seven9 it's same issue with https://github.com/Rabbit-Converter/Rabbit/issues/32#issuecomment-247559880 . I will close and please check at https://github.com/Rabbit-Converter/Rabbit/issues/32#issuecomment-247559880

**Comment by saturngod** [comment]
@seven9 if you are urgent , please use it from Rabbit master branch.

https://github.com/Rabbit-Converter/Rabbit/blob/master/other-lang/php/Rabbit.php

**Comment by saturngod** [comment]
@seven9 , test code is http://sandbox.onlinephpfunctions.com/code/0a44bf3a763318e8d8dcb6a305904ebe180ec027

**Comment by yenyint** [comment]
@saturngod  Thanks Bro
